### ISSUE TITLE
Define missing in german

### ISSUE THREAD

**Issue by cesagonchu** [ggoffy/wgtimelines#13]
Define missing in german:

wgtimelines/german/admin.php

define('_AM_WGTIMELINES_RATING_ADD', '');
define('_AM_WGTIMELINES_RATING_EDIT', '');
define('_AM_WGTIMELINES_RATING_ITEMID', '');
define('_AM_WGTIMELINES_RATING_VALUE', '');
define('_AM_WGTIMELINES_RATING_UID', '');
define('_AM_WGTIMELINES_RATING_IP', '');
define('_AM_WGTIMELINES_RATING_DATE', '');

![image](https://cloud.githubusercontent.com/assets/4613970/23559694/2029c9bc-0038-11e7-8ab5-05cdba8e0989.png)

and
wgtimelines\german\help\help.html

is different from:

wgtimelines\english\help\help.html

**Comment by ggoffy** [comment]
hi cesagoncho

the defines in english are not needed, delete them.

the help files are in the same structure now.

Thank you
