### ISSUE TITLE
Minimum compatible xoops version

### ISSUE THREAD

**Issue by cesagonchu** [ggoffy/wgtimelines#14]
If this module is compatible, at least, with Xoops 2.5.8, so please go to:

**xoops_version.php** line 44

and replace:

$modversion['min_xoops']           = '2.5.7';

with

$modversion['min_xoops']           = '2.5.8';

**Comment by ggoffy** [comment]
Hi cesagonchu 

this module works with both versions and I tested it with both and also with PHP 5.6 and 7
therefore minimum xoops version 2.5.7 is ok.

kind regards
Goffy

**Comment by cesagonchu** [comment]
Ok, I said that because of your README.md  :-)

**Comment by ggoffy** [comment]
Oh, sorry, this readme added mamba and I didnt check exactly. I will change. Thank you.

**Comment by cesagonchu** [comment]
No pb, thank you ;-)
