### ISSUE TITLE
Typo: foruploads

### ISSUE THREAD

**Issue by cesagonchu** [ggoffy/wgtimelines#15]
wgtimelines/language/english/modinfo.php
Line 47

Typo: foruploads

replace
define('_MI_WGTIMELINES_MAXSIZE_DESC', 'Please define the maximum file size **foruploads file**. You have to enter the value for bytes (10485760 = 1 MB)');

with:

define('_MI_WGTIMELINES_MAXSIZE_DESC', 'Please define the maximum file size **for uploaded files**. You have to enter the value for bytes (10485760 = 1 MB)');

**Comment by ggoffy** [comment]
hi, done, thank you
