### ISSUE TITLE
Language conversion

### ISSUE THREAD

**Issue by cesagonchu** [ggoffy/wgtimelines#16]
A) The language conversion of the module is not finished.
As you can see here:
wgtimelines/admin/templates.php

![image](https://cloud.githubusercontent.com/assets/4613970/24086838/fee01ee6-0d16-11e7-9fc9-920e6869219a.png)
Please, can you create language definitions for these sentences that are located in:
wgtimelines/sql/mysql.sql
wgtimelines/sql/update.sql

They would ideally go here:
wgtimelines/language/english/

___

B) Please, can you also create a language definition for this sentence that is located in:

wgtimelines/xoops_version.php
line 175

![image](https://cloud.githubusercontent.com/assets/4613970/24092736/684c9290-0d50-11e7-9067-b3db7b3f5097.png)

**Comment by ggoffy** [comment]
Hi cesagonchu

B) is done
A) here I have first to think about how to solve this

**Comment by cesagonchu** [comment]
Thank you very much!

No problem, take your time ;-)

**Comment by ggoffy** [comment]
Hi cesagonchu

please download latest version

**Comment by cesagonchu** [comment]
I will test soon, sorry for the delay.
