### ISSUE TITLE
Problem overrides templates

### ISSUE THREAD

**Issue by frgod** [ggoffy/wgtimelines#17]
Hello,

I put my overides in my theme folder, and it don't work. I put my files in mythemes/modules/wgtimelines/

Is it normal ?

I have Xoops 2.5.9

**Comment by ggoffy** [comment]
normally it must work (I do it in the same way ;) ). maybe you have to clean cache.

did you set option "Check templates for modifications?" in System/Preferences/General Settings to "Yes"

did you put the files directly into mythemes/modules/wgtimelines/?
or did you move the complete folder, so you have now "mythemes/modules/wgtimelines/templates/"

**Comment by frgod** [comment]
I put directly files (tpl) into mythemes/modules/wgtimelines/ and css into mythemes/modules/wgtimelines/css/

Option is setting to yes, and it works with others modules

**Comment by frgod** [comment]
I removed it and re installe it and it seems ok. Sorry

**Comment by frgod** [comment]
Ok, I removed it and re install it and it seems ok. Sorry
