### ISSUE TITLE
Error when creating Timelines in tab Timelines

### ISSUE THREAD

**Issue by alain01** [ggoffy/wgtimelines#18]
wgtimelines 1.11 RC1

Version minimum de PHP requise : 5.5 (votre version est la 7.3.6) 
MYSQL La version minimum requise est : 5.1 (votre version est actuellement 5.6.43-log)
La version minimum de XOOPS requise est : 2.5.7 (votre version est actuellement 2.5.11-Alpha1) 
La version minimum de ModuleAdmin requise est : 1.1 (votre version est actuellement 1.2) 
Le répertoire '/uploads/wgtimelines' existe 
Le dossier '/uploads/wgtimelines' doit être en chmod '777' (il est maintenant défini en 777). 
Le répertoire /uploads/wgtimelines/images/' existe 
Le dossier '/uploads/wgtimelines/images/' doit être en chmod '777' (il est maintenant défini en 777). 
Le répertoire '/uploads/wgtimelines/images/timelines/' existe 
Le dossier '/uploads/wgtimelines/images/timelines/' doit être en chmod '777' (il est maintenant défini en 777). 
Le répertoire '/uploads/wgtimelines/images/items/' existe 
Le dossier '/uploads/wgtimelines/images/items/' doit être en chmod '777' (il est maintenant défini en 777). 

- Installation : ok
- Tab Timelines ok (empty, no timeline)
- Add new Timelines, write informations in several fields : Error when i click on button to create a new timeline

Notification: Array to string conversion dans le fichier /modules/wgtimelines/class/helper.php ligne 106

and no timeline is created.

- No problem to create items

**Comment by alain01** [comment]
Oooups, sorry,
"Hello goffy" ! ;-)

**Comment by ggoffy** [comment]
fixed. please test

**Comment by alain01** [comment]
ha, it works ! 
thank you !
