### ISSUE TITLE
space with link

### ISSUE THREAD

**Issue by alain01** [ggoffy/wgtimelines#20]
Hi Goffy, great work, as usually.
i noticed 1 little thing : 

/wgtimelines/index.php?op=list&tl_id=1

There is a link for the space between icon "edit" and "delete"

**Comment by alain01** [comment]
Same with : 
wgtimelines/admin/timelines.php 
admin side, tab "Timelines", column "Action"

Same with :
wgtimelines/admin/templates.php
admin side, tab "Timelines", column "Action"

Same with :
wgtimelines/admin/items.php
admin side, tab "Timelines", column "Action"

**Comment by ggoffy** [comment]
hi
are you meaning displaying with firefox?
https://blog.nightly.mozilla.org/2016/10/17/devtools-now-display-white-space-text-nodes-in-the-dom-inspector/

**Comment by alain01** [comment]
No, see my image
![Capture](https://user-images.githubusercontent.com/5336960/69636275-87374680-1056-11ea-8418-79d7f988e17e.PNG)

**Comment by ggoffy** [comment]
which browser?

**Comment by alain01** [comment]
Chrome, but think it's same with firefox

**Comment by ggoffy** [comment]
![grafik](https://user-images.githubusercontent.com/7547661/69636530-180e2200-1057-11ea-8964-fb244eb3aa64.png)

**Comment by alain01** [comment]
it's the same trouble like here : 
https://github.com/XOOPS/XoopsCore25/commit/70ff92434ec1b83192ceee34830f67c8b0d3ed26

**Comment by ggoffy** [comment]
i have changed tpl into:
![grafik](https://user-images.githubusercontent.com/7547661/69636917-ef3a5c80-1057-11ea-91c7-7fd9067c3edf.png)

but there are still these empty spaces
![grafik](https://user-images.githubusercontent.com/7547661/69636987-1002b200-1058-11ea-8bba-a0229218c4e6.png)

?????

**Comment by ggoffy** [comment]
even in my Chrome it looks like this:
![grafik](https://user-images.githubusercontent.com/7547661/69637199-77206680-1058-11ea-8283-8fe4d4d49aac.png)

**Comment by alain01** [comment]
no no,
move your mouse hover , between icons

**Comment by alain01** [comment]
ues, the problem is the cariage return, it makes a "space link"
mage killed the problem in th core, system admin tab, here : https://github.com/XOOPS/XoopsCore25/commit/70ff92434ec1b83192ceee34830f67c8b0d3ed26

**Comment by ggoffy** [comment]
ok. can you test latest version from github

**Comment by alain01** [comment]
Perfect ! Great ! 
But now, you know that you have same troubles with your other modules ;-)))))

**Comment by ggoffy** [comment]
if you know the problem then solution can be made :)

**Comment by ggoffy** [comment]
thanks
