### ISSUE TITLE
Display a List for icons, page items

### ISSUE THREAD

**Issue by alain01** [ggoffy/wgtimelines#21]
Hi,
wgtimelines/admin/items.php?op=edit&item_id=16 (example)

"Icon" 
Will be only used, if option 'Badge content' is set corresponding
It 's difficult to see them, cause icon + text are melted.
May be you could display icons in a table,
but Achtung, 
How is it display when we resize web browser ? 

;-)

**Comment by ggoffy** [comment]
hi. I am not sure whether I understand you well. Do you mean that all option are in a long line?

**Comment by alain01** [comment]
yes, it's difficult to see or search one icon, with text around

may be, dont display text, or display icons in several columns

**Comment by ggoffy** [comment]
would it be nicer like this:
![grafik](https://user-images.githubusercontent.com/7547661/69653540-ad1f1400-1073-11ea-9e39-c65951a8ea22.png)

**Comment by alain01** [comment]
humm, not really
, it's same as before ! 
Is it possible to align icons, align text, (table or div) ?

**Comment by alain01** [comment]
Here a example but in this exemple, icons are too small regarding text
![set-fontawesome](https://user-images.githubusercontent.com/5336960/69654898-da6cc180-1075-11ea-9f2b-82746041c52a.png)

**Comment by ggoffy** [comment]
not really, as long I use xoops form  I am fixed by xoops itself, so i cannot display form elements as table.
but I can fix the widht
![grafik](https://user-images.githubusercontent.com/7547661/69655027-0a1bc980-1076-11ea-9899-8befefbbf3c1.png)

**Comment by alain01** [comment]
ok better, yes, except the 1st line. 
I think no need bordure, 
we need a light page to help us to find quickly what icon we will use.

**Comment by alain01** [comment]
Goffy, it's not for css code, (u get the form) so i think we dont need to see the text, no  ?

**Comment by alain01** [comment]
ha, or text is usefull to search via web page search (CTRL + "F")...

**Comment by ggoffy** [comment]
I uploaded last version.
I used xoops radio, but I hide the radio and transform the label into a button, so it looks like toggle buttons. In the first line there is the indent because of non-visible radio, but for the moment I found no solution.

**Comment by alain01** [comment]
Ok i understand.
So, not perfect, but more readable, no, isnt' it ?  ;-)

**Comment by ggoffy** [comment]
now it should looks also nice :)
![grafik](https://user-images.githubusercontent.com/7547661/69660238-2a508600-1080-11ea-95e7-9f447e31bd44.png)

**Comment by alain01** [comment]
Waouuuuu,
Now i can tell that's it's Amazing.
Great work,
Now you have improved this page, vert readable!

**Comment by ggoffy** [comment]
thanks
