### ISSUE TITLE
tpl_author

### ISSUE THREAD

**Issue by mambax7** [ggoffy/wgtimelines#3]
in \include\search.inc.php on line 35
It should be: tpl_author

**Comment by ggoffy** [comment]
the author is not a xoops user.
Do you think it make sense to add a submitter, because normally users can only change settings, not adding new templates.

**Comment by mambax7** [comment]
But the author should be a XOOPS User, right? I would have to understand better the roles that you envision...

**Comment by ggoffy** [comment]
no, it is only for information, who delevoped this templated. 
If you have a good idea for a new template, that I can note als author: Mamba/Goffy ;-)
