### ISSUE TITLE
Bug in paging

### ISSUE THREAD

**Issue by mambax7** [ggoffy/wgtimelines#4]
I start in one timeline:
http://xoops.org/modules/wgtimelines/index.php?tl_id=2

but when I go to the paging at the bottom, on the page 2 the "tl_id" is missing:

http://xoops.org/modules/wgtimelines/index.php?start=10&op=list&limit=10

**Comment by ggoffy** [comment]
fixed with next version

**Comment by ggoffy** [comment]
thanks

**Comment by mambax7** [comment]
When I go to:
http://xoops.org/modules/wgtimelines/index.php?start=10&op=list&limit=10&tl_id=2
I am getting:
Notice: Undefined index: xoopsTpl in file /modules/wgtimelines/index.php line 213

**Comment by ggoffy** [comment]
fixed
