### ISSUE TITLE
Request: edit icon on the front-end

### ISSUE THREAD

**Issue by mambax7** [ggoffy/wgtimelines#5]
Feature request: 

I would like to be able to edit/delete items in the front end.

Right now, there is no option:
http://xoops.org/modules/wgtimelines/index.php

**Comment by ggoffy** [comment]
next version have the possibility that you link an item with "no timeline"
now you don't have to delete on admin side

should I add additionally an "online"-field to table itemsa?

**Comment by ggoffy** [comment]
in new version you can decide for each item, whether it should be already online or not.

**Comment by mambax7** [comment]
Yes, but now that I updated the module, all of them are now set to Offline :(

In the module update for this version, you should set "offline" as "on"

**Comment by mambax7** [comment]
Additional issue: I go to the last page to set it to "on" and as soon as I click on it, it gets me back to the first  page, so I have to go back and forth for each individual change :(

**Comment by mambax7** [comment]
I would like to have these icons visible for individual item:

![image](https://cloud.githubusercontent.com/assets/613686/20876565/1575ed08-ba91-11e6-948a-cfb1813f6e1f.png)

**Comment by mambax7** [comment]
You could also place these icons on top. 
In addition, the Title should be made to a link to the individual view of the item:

![image](https://cloud.githubusercontent.com/assets/613686/20876601/4c1e8f18-ba91-11e6-8902-55033d636b8f.png)

**Comment by ggoffy** [comment]
> Yes, but now that I updated the module, all of them are now set to Offline :(

goto database and run: 
UPDATE `{your prefix}_wgtimelines_items` SET `item_online` = '1';

**Comment by mambax7** [comment]
>But this makes IMO only sense if we make also the possibility to limit the text on the timeline (e.g. 200 characters) and show a "read more" button for details.

You can add as an option to limit the text. But regardless of limiting or not, it makes sense if I want to post this individual item on Facebook, or email it to somebody. 

> then I can also insert a counter for reads

that would be very nice. You could also add "rating" or "like it"

**Comment by ggoffy** [comment]
> You can add as an option to limit the text.
> counter for reads

is already included :-)

>You could also add "rating" or "like it"

yes

**Comment by ggoffy** [comment]
rating is included
