### ISSUE TITLE
Title of the Module hardcoded

### ISSUE THREAD

**Issue by mambax7** [ggoffy/wgtimelines#6]
I've changed the name to "XOOPS Awards", but it is not reflected in the Timeline:

![image](https://cloud.githubusercontent.com/assets/613686/20876443/0abdffbe-ba90-11e6-9bd4-8a8de1cb1d5e.png)

**Comment by ggoffy** [comment]
the breadcrumb menu is created as defined by tdmcreate module
`$xoBreadcrumbs[] = array('title' => _MA_WGTIMELINES_TITLE, 'link' => WGTIMELINES_URL . '/');`

you have to change _MA_WGTIMELINES_TITLE

**Comment by mambax7** [comment]
Thanks, it works!
