### ISSUE TITLE
Module home view

### ISSUE THREAD

**Issue by mambax7** [ggoffy/wgtimelines#8]
I am in the "home" view of the module, but it forces the see one Timeline, i.e. I have no idea what other timelines could be available. Even if I click on the Home icon, or on the "wgTimelines", it is still "XOOPS Innovators".
It would be nice to have in the Home a selection of the available timelines

![image](https://cloud.githubusercontent.com/assets/613686/20877049/151bf85e-ba94-11e6-9328-ad98043c51c0.png)

**Comment by ggoffy** [comment]
I will implement the same as in wgTeams:
an option, what should happen if someone click on home - show list or show first one or show all

**Comment by ggoffy** [comment]
implemented with version 1.05

**Comment by mambax7** [comment]
Thanks, it works!
