### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by GregMage** [ggoffy/wgtimelines#9]
In administration I have 2 lines

![image](https://cloud.githubusercontent.com/assets/16707432/22176506/a6b2c020-e00c-11e6-9f1c-0cfef1ed8158.png)

But not here:

![image](https://cloud.githubusercontent.com/assets/16707432/22176502/93a254c8-e00c-11e6-948b-f9fcb1895e1d.png)

**Comment by ggoffy** [comment]
Hi
you have two possibilites:
1) if you are using the plain text editor (like you have done), you should add html code, e.g. 
```
<h3>this is my h3 heading line</h3>
<p>this is my first line</p>
<p>this is my second line</p>
```

or 

2) you go to wgtimelines preferences and change editor to an html-editor (like tinymce, which is normally included in xoops core)

**Comment by GregMage** [comment]
I know, but it's not fair! I make the change to show you. This is a small detail but it is important to change that.

**Comment by ggoffy** [comment]
Hi, I'm not sure whether I unstand you right: what should I change? The dhtml-editor in xoops core?

**Comment by GregMage** [comment]
I'll make the change to show you.

If you write:
![image](https://cloud.githubusercontent.com/assets/16707432/22183847/8c456808-e0c7-11e6-9ac8-077d33c999b5.png)

![image](https://cloud.githubusercontent.com/assets/16707432/22183851/ac87ef3c-e0c7-11e6-8a0d-84b878b50fd3.png)

The html is not allowed with "Plain text" and "DHTML Form witx xCode".

To authorize it must be added this line in your class:

`$this->initVar('dohtml', XOBJ_DTYPE_INT, 1, false);`

To display the text properly, use:

`$ret['content'] = $this->getVar('item_content', 'show');`

and not:

`$ret['content'] = $this->getVar('item_content', 'n');`

**Comment by ggoffy** [comment]
Hi Mage

I tried you changes. Dhtml-editor works, but if I use tinymce and text like this:
![grafik](https://cloud.githubusercontent.com/assets/7547661/22185603/2f59155a-e0e9-11e6-9d7f-413934ea593d.png)
I get on user side
![grafik](https://cloud.githubusercontent.com/assets/7547661/22185612/444e3a94-e0e9-11e6-8c88-49c7f0879039.png)
The blank lines are gone away.

how to solve this?

**Comment by GregMage** [comment]
![image](https://cloud.githubusercontent.com/assets/16707432/22195064/3dcccf7a-e146-11e6-8b63-b58fc0b14ca6.png)

If we look at the html:
`<p>Test ligne 1</p><p>Test ligne 2</p><p></p><p>Test ligne 3</p><p></p><p></p><p>Test ligne 6</p>`

As we use html, it is normal to have this result.

The problem comes from tinymce. I'll talk about it with Richard. We can not do otherwise ...

**Comment by GregMage** [comment]
This is normal behavior:

[https://github.com/XOOPS/XoopsCore25/issues/303](https://github.com/XOOPS/XoopsCore25/issues/303)
